version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo Installing source NPM dependencies...
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - 'npm run build-prod'
            - echo Test started on `date`
            - npm run test-once
            - echo Lint started on `date`
            - npm run lint
            - 'aws s3 cp dist s3://${S3_BUCKET} --recursive'
            - echo Build completed on `date`
